name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Add permissions for release creation
permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['18.17.0']

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Verify Node.js version
      run: node -v
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linter
      run: npm run lint
    
    - name: Build
      run: npm run build

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.17.0'
        cache: 'npm'
    
    - name: Verify Node.js version
      run: node -v
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
    
    - name: Debug build output
      run: |
        echo "Current directory contents:"
        ls -la
        echo "Checking for build output directories:"
        ls -la dist out build .next 2>/dev/null || true
    
    - name: Create ZIP file
      run: |
        # Check for common build output directories
        if [ -d "dist" ]; then
          echo "Found 'dist' directory, creating ZIP from it"
          cd dist && zip -r ../extension.zip .
        elif [ -d "out" ]; then
          echo "Found 'out' directory, creating ZIP from it"
          cd out && zip -r ../extension.zip .
        elif [ -d ".next" ]; then
          echo "Found '.next' directory, creating ZIP from it"
          cd .next && zip -r ../extension.zip .
        else
          echo "Error: No build output directory found!"
          echo "Expected one of: dist/, out/, or .next/"
          exit 1
        fi
    
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        draft: false
        prerelease: false
        files: extension.zip
        generate_release_notes: true 